<?php 
$title = 'Profile settings';
$this->headtitle($title);
?>

<h1><?= $this->escapehtml($title); ?></h1>

<?php 
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'user',
        array(
            'action' => 'account',
            'id'     => $this->id            
        )
    ));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo '<dl class="zend_form">';    
    echo $this->formHidden($form->get('id'));
    echo '<dt>' . $this->formLabel($form->get('username')) . '</dt>';
    echo '<dd>';
    echo $this->formInput($form->get('username'));
    echo $this->formElementErrors($form->get('username'));
    echo '</dd>';
    echo '<dt>' . $this->formLabel($form->get('password')) . '</dt>';
    echo '<dd>';
    echo $this->formInput($form->get('password'));
    echo $this->formElementErrors($form->get('password'));
    echo '</dd>';
    echo '<dd>';
    echo $this->formsubmit($form->get('submit')->setAttribute('class', 'btn btn-inverse'));
    echo '&nbsp; <a class="btn" href="' . $this->url('user') . '">' . $this->translate('Cancel') . '</a>';
    echo '</dd>';
    echo '<dl>';
    echo $this->form()->closeTag();
?>
