<?php 
$title = 'Welcome !';
$this->headtitle($title);
?>

<h1><?php echo $this->escapehtml($title); ?></h1>
<p>
    <a href="<?= $this->url('user', array('action'=>'account', 'id' => $user->id));?>"><?= $this->translate('Settings'); ?></a> |
    <a href="<?= $this->url('user', array('action' => 'signout')); ?>"><?= $this->translate('Log out'); ?></a>
</p>
<br/>
<p>
    Hi, <strong><?= $user->username ?></strong> !
</p>
